### ISSUE TITLE
possible typo on line 86 of README.md

### ISSUE THREAD

**Issue by dm-wyncode** [ericelliott/tinyapp#3]
I was reading _Programming JavaScript Applications_ which led me here.

I was trying out some of the sample code and may have discovered a typo in line 86 of the read me that also exists on [the website](http://tinyappjs.com/). (Using jslint in Vim alerted me to it.)

> `hello: function hello() {`

should be `hello = function hello() {`

Thanks for sharing such useful information.

**Comment by ericelliott** [comment]
Oops, you're right. Would you like to make a pull request?

**Comment by dm-wyncode** [comment]
Yes! Done.
